Repository codeready-toolchain/api, pull requests merged in 2019-06, with the labels that each got.

#6 Add resourceVersion to MasterUserRecord status
  .gitignore
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#10 Add UserID to MasterUserRecord and UserAccount
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/S

#11 add useracc status const
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, lgtm, size/XS

#12 Rename ResourceVersion to SyncIndex in MasterUserRecord
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Labels: approved, size/XS

#13 feat: introduce StatusUserAccount type
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  tools.go
Labels: approved, size/S

#14 fix: rename also Status.ResourceVersion to SyncIndex in MasterUserRecord
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Labels: approved, size/XS
