Repository codeready-toolchain/api, pull requests merged in 2019-10, with the labels that each got.

#39 feat(CRT-227): add script & target that generates CSV for host-operator
  .github/pull_request_template.md
  make/generate.mk
  scripts/olm-catalog.sh
Labels: approved, size/L

#40 Update go to 1.13
  README.adoc
  go.mod
Labels: approved, size/XS

#41 Short name 'tier' for NSTemplateTier CRD
  pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
Labels: approved, size/XS

#43 chore(CRT-281): add CustomResourceDefinition types into scheme builder
  pkg/apis/addtoscheme_kubefed_v1beta1.go
  pkg/apis/addtoscheme_toolchain_v1alpha1.go
  pkg/apis/apis.go
  tools.go
Labels: approved, size/M

#42 chore: make olm-catalog.sh script mac compatible
  scripts/olm-catalog.sh
Labels: approved, size/S

#44 fix CRD generation and fix openapi validations
  go.mod
  go.sum
  make/generate.mk
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  scripts/olm-catalog.sh
  tools.go
Labels: approved, size/M

#46 feat(CRT-228): modify script so it creates CSV and hack files for member-operator
  make/generate.mk
  scripts/olm-catalog.sh
Labels: approved, size/XS

#45 Added CompliantUsername to UserSignup API type
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/S

#47 configure golangci-lint new timeout
  .golangci.yml
Labels: approved, size/XS

#48 Removed UserID field from spec
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/S

#50 chore(CRT-331): rename operators to toolchain-host-operator and toolchain-member-operator
  README.adoc
  scripts/olm-catalog.sh
Labels: approved, size/S
