Repository codeready-toolchain/api, pull requests merged in 2019-11, with the labels that each got.

#51 Switch to controller-tools 0.2.1
  go.mod
  go.sum
  make/generate.mk
  openshift-ci/Dockerfile.tools
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/L

#55 fix: use correct key when verifying operator-sdk binary
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#54 chore: drop 0.0.0 csv template thanks to operator-sdk 0.11.0
  scripts/olm-catalog.sh
Labels: approved, size/S

#52 chore: refactoring of olm script to make it ready for pushing to quay
  make/generate.mk
  scripts/olm-catalog-generate.sh
  scripts/olm-catalog.sh
  scripts/olm-setup.sh
Labels: approved, size/L

#53 Creates a script that generates operator bundle and push it to quay
  scripts/olm-setup.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/M

#56 Update kubefed to the latest commit from master
  go.mod
  go.sum
Labels: approved, size/XS

#57 Generate KubeFedCluster CRD
  .github/pull_request_template.md
  go.mod
  go.sum
  make/generate.mk
  tools.go
Labels: approved, size/M

#58 fix(olm scripts): fix replace,git command and params for nightly
  scripts/olm-setup.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/M

#60 fix: grep shouldn't fail when doesn't find replace clause & improve help
  scripts/olm-catalog-generate.sh
  scripts/olm-setup.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/M

#49 CRT-330 remove CompliantUsername field from UserSignup.Spec
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/M

#59 Add details about cluster for UserAccounts in MUR
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
Labels: approved, size/M

#62 chore: update tools in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#63 fix: add missing git community source
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#64 add jq to CI tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#61 feat(CRT-352): create RegistrationService CRD
  make/generate.mk
  pkg/apis/toolchain/v1alpha1/registrationservice_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L
