Repository codeready-toolchain/api, pull requests merged in 2019-08, with the labels that each got.

#22 Fix vendor issue
  go.mod
  go.sum
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/M

#25 fix: register KubeFed types
  go.mod
  go.sum
  pkg/apis/addtoscheme_kubefed_v1beta1.go
Labels: approved, size/S

#27 Modify condition types for UserSignup
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/XS

#28 Preserve custom fields in crds
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/S

#29 add gofmt linter
  .golangci.yml
Labels: approved, size/XS
