Repository codeready-toolchain/api, pull requests merged in 2019-12, with the labels that each got.

#65 feat(CRT-361): add target copying reg-service deployment to host repo
  make/generate.mk
Labels: approved, size/XS

#66 Remove deprecated TargetCluster from MUR status
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Labels: approved, size/XS

#68 fix: use commit- prefix in the pre-release part
  scripts/push-to-quay-nightly.sh
Labels: approved, size/XS

#67 feat: add operator-name param to CSV generation options & createdAt relpacement
  scripts/olm-setup.sh
Labels: approved, size/S

#69 Adding usersignup email
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/XS

#70 fix: rename IMAGE var to IMAGE_IN_CSV to avoid mismatch
  scripts/olm-setup.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/XS

#71 process all yaml files in deploy/crds
  make/go-header.txt
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  scripts/olm-setup.sh
Labels: approved, size/XS

#72 feat: support operators with only allnamespaces install mode enabled
  scripts/olm-setup.sh
Labels: approved, size/S

#73 CRT-373 add Banned property to MasterUserRecord
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/S

#74 Add Deactivated property to UserSignup
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/S

#75 Add Che URL to MUR status
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Labels: approved, size/XS

#76 feat: add scripts for generating manifests
  scripts/create-release-bundle.sh
  scripts/olm-setup.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/L

#77 fix: don't add replace clause for the same version
  scripts/create-release-bundle.sh
  scripts/olm-setup.sh
Labels: approved, size/S

#78 feat: add script for pushing manifests to quay
  scripts/create-release-bundle.sh
  scripts/olm-setup.sh
  scripts/push-to-quay-manifests.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/M

#79 fix(scripts): don't remove empty lines from CSV
  scripts/olm-setup.sh
Labels: approved, size/XS
