Repository codeready-toolchain/api, pull requests merged in 2019-07, with the labels that each got.

#15 Add conditions to UserAccount & MasterUserRecord statuses
  go.mod
  pkg/apis/toolchain/v1alpha1/conditions.go
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#16 Add UserProvisionRequest
  make/generate.mk
  pkg/apis/toolchain/v1alpha1/userprovisionrequest_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#18 Rename UserProvisionRequest to UserSignup
  make/generate.mk
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#17 Fix Status Condition comments
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/XS

#19 Cleanup UserAccountConditions
  pkg/apis/toolchain/v1alpha1/conditions.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/S

#21 Rename UserSignupRequestList -> UserSignupList
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#24 pr template added
  .github/pull_request_template.md
Labels: approved, lgtm, size/S
