Repository codeready-toolchain/api, pull requests merged in 2019-09, with the labels that each got.

#30 fix printcolumns tags
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/S

#32 support ready condition for nstemplateset
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/M

#31 Added username field to UserSignup spec
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/S

#33 chore: add code coverage for tests
  .codecov.yaml
  README.adoc
  make/go.mk
  make/out.mk
  make/test.mk
Labels: approved, size/L

#34 added CompareTo method to NSTmplSetSpec comparision
  go.mod
  go.sum
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types_test.go
Labels: approved, lgtm, size/L

#35 minor change - second now pass by value
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types_test.go
Labels: approved, size/S

#36 Pin to kube 1.14 & cleanup
  go.mod
  go.sum
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#37 refactor NSTemplateSet/NSTemplateTier Namespace type
  go.mod
  go.sum
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types_test.go
  pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  tools.go
Labels: approved, size/L

#38 chore: add crd suffix to CRD file names-it's expected by operator-sdk csv generator
  make/generate.mk
Labels: approved, size/XS
