Repository codeready-toolchain/api, pull requests merged in 2020-02, with the labels that each got.

#97 CRT-396 add a label key for UserSignup email hash value
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/XS

#99 fix: check the availability of yq when it's needed
  scripts/enrich-by-envs-from-yaml.sh
Labels: approved, size/S

#98 Fix the naming of constant UserSignupUserEmailHashLabelKey
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/XS

#101 fix: use api call to get digest & create ConfigMap first
  scripts/generate-deploy-hack.sh
  scripts/olm-setup.sh
Labels: approved, size/M

#100 Refactor masteruserrecord spec
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#102 feat: add possibility to specify quay namespace via parameter
  scripts/create-release-bundle.sh
  scripts/olm-setup.sh
  scripts/push-to-quay-manifests.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/M

#103 chore: add README.adoc into the scripts directory
  scripts/README.adoc
  scripts/create-release-bundle.sh
  scripts/olm-setup.sh
  scripts/push-to-quay-manifest.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/L

#105 removing deprecated fields disabled and userid from useraccountspecem…
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/S

#106 Ignore zz_*.go generated files in codecov reports
  .codecov.yaml
Labels: approved, size/XS

#107 Update to Kube 1.16.2
  go.mod
  go.sum
  pkg/apis/toolchain/v1alpha1/banneduser_types.go
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
  pkg/apis/toolchain/v1alpha1/registrationservice_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/XL

#108 Mur disabled reason
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
Labels: approved, size/S

#110 fix(CRT-472): wait until image digest is available or fail if is not found
  scripts/olm-setup.sh
Labels: approved, size/S
