Repository codeready-toolchain/api, pull requests merged in 2020-01, with the labels that each got.

#80 feat: separate generation of deployment hack file to a script
  scripts/create-release-bundle.sh
  scripts/generate-deploy-hack.sh
  scripts/olm-setup.sh
Labels: approved, size/L

#82 chore: update openshift/api to release-4.2
  go.mod
  go.sum
Labels: approved, size/XS

#83 chore: api scheme should contain only CRs
  pkg/apis/apis.go
Labels: approved, size/XS

#84 CRT-395 add BannedUser CRD
  go.mod
  make/generate.mk
  pkg/apis/toolchain/v1alpha1/banneduser_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#85 Add NSTemplateSet label keys consts
  pkg/apis/toolchain/v1alpha1/banneduser_types.go
  pkg/apis/toolchain/v1alpha1/labels.go
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/S

#86 Adding reasons
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/S

#87 renaming reason consts to add prefix UserAccount
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/S

#88 feat(CRT-363): add script for enriching CSV by envs from config yaml file
  scripts/enrich-by-envs-from-yaml.sh
  scripts/olm-setup.sh
Labels: approved, size/L

#89 chore: store reg-service parameters in a map
  pkg/apis/toolchain/v1alpha1/registrationservice_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/M

#90 feat(CRT-362): support embedded repositories in CD script/process
  scripts/create-release-bundle.sh
  scripts/olm-setup.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/M

#91 fix: use correct paths when fetching scripts from GH
  scripts/create-release-bundle.sh
  scripts/olm-catalog-generate.sh
  scripts/olm-setup.sh
  scripts/push-to-quay-manifests.sh
  scripts/push-to-quay-nightly.sh
Labels: approved, size/S

#93 chore: add olm.skipRange for nightly releases
  scripts/olm-setup.sh
Labels: approved, size/XS

#92 chore(CRT-427): use digest instead of tag for defining docker images
  scripts/olm-setup.sh
Labels: approved, size/XS

#94 Adding disabling reason
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/XS

#95 adding terminating reason
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/XS

#96 move NSTemplateSet status reasons to 'api' repo
  pkg/apis/toolchain/v1alpha1/banneduser_types.go
  pkg/apis/toolchain/v1alpha1/finalizer.go
  pkg/apis/toolchain/v1alpha1/labels.go
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/M
