Repository codeready-toolchain/api, pull requests merged in 2020-03, with the labels that each got.

#112 Registration service reasons
  pkg/apis/toolchain/v1alpha1/registrationservice_types.go
Labels: approved, size/XS

#111 chore: add ns update related label and reasons
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/XS

#113 Usersignup reasons
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/S

#115 Reusing consts
  pkg/apis/toolchain/v1alpha1/conditions.go
  pkg/apis/toolchain/v1alpha1/masteruserrecord_types.go
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/useraccount_types.go
Labels: approved, size/M

#114 feat(CRT-478): create ChangeTierRequest that will ensure tier change
  make/generate.mk
  pkg/apis/toolchain/v1alpha1/changetierrequest_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/L

#116 add 'clusterResourceQuota' field in NSTemplateTier
  pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/M

#118 Make cluster resources a pointer so it's easy to use it as optional field
  pkg/apis/toolchain/v1alpha1/nstemplatetier_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
Labels: approved, size/XS

#119 Moved constants from host operator
  pkg/apis/toolchain/v1alpha1/usersignup_types.go
Labels: approved, size/XS

#117 add 'clusterResources' field in NSTemplateSet
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/M

#120 add reason for cluster resource provisioning error
  pkg/apis/toolchain/v1alpha1/nstemplateset_types.go
Labels: approved

#109 Update to operator-sdk 0.15
  README.adoc
  cmd/manager/main.go
  openshift-ci/Dockerfile.tools
  pkg/apis/toolchain/v1alpha1/changetierrequest_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  scripts/README.adoc
  scripts/olm-setup.sh
Labels: approved, size/M

#121 Fix operator-sdk key
  openshift-ci/Dockerfile.tools
Labels: approved
